name: Provider Build
on: push
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  build_provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_wrapper: false
      - name: Get Provider Versions
        run: curl -s https://registry.terraform.io/v1/providers/hashicorp/aws/versions | jq -r '.versions | .[] | .version'
      - name: Init Terraform
        run: terraform init
      - name: Export provider schema
        run: terraform providers schema -json > schema.json