name: Provider Build
on: push
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  build_provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_wrapper: false
      - name: Get Provider Versions
        id: provider_version
        run: echo "::set-output name=version::`curl -s https://registry.terraform.io/v1/providers/hashicorp/aws/versions | jq -r '.versions | .[-1] | .version'`"
      - name: Update Provider Version
        run: sed -i 's/%aws_version%/${{ steps.provider_version.outputs.version }}/g' providers.tf.json
      - name: Init Terraform
        run: terraform init
      - name: Export provider schema
        run: terraform providers schema -json > schema.json
      - name: Build Terrastack
        run: yarn && yarn build
      - name: Create Provider schema
        run: packages/terrastack-cli/bin/terrastack import -i schema.json -p ${{ steps.provider_version.outputs.version }}
      - name: Generated artifact
        uses: actions/upload-artifact@v2
        with:
          name: AWS Provider TS
          path: .generated/aws